In [1]:
## Seismic Analysis Impact on PCI - Test Population
## By: Fervis Lauan
## Date: 09-29-17
##----------------------------------------------------

# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import requests
from census import Census
from us import states

In [3]:
##################################
# Get Test Population
##################################



ziplst=[96130,89406,95501,93117,82520,92247,73013,95422,73020,95540,75964,93555,93561,92284,98807,75652,89433,93212,90275,93436,96150]

ctr=1
for zip in ziplst:   
    yr=2012            
    while yr<=2013:
        try:
            c = Census("85ac64b6b5a9c0901b00329d1ef41f0c53ccfc98", year=yr)
            census_data = c.acs5.get(("NAME",
                                              "B01003_001E", 
                                              "B01002_001E",
                                              "B19013_001E",
                                              "B19301_001E",
                                              "B17001_002E",
                                              "B23025_002E",
                                              "B23025_005E",
                                              "B25077_001E",
                                              "B25064_001E",
                                              "C24010_009E",
                                              "C24010_016E",
                                              "C24010_019E",
                                              "C24010_022E",
                                              "C24010_023E",
                                              "C24010_025E",
                                              "C24010_030E",
                                              "C24010_032E",
                                              "C24010_045E",
                                              "C24010_052E",
                                              "C24010_055E",
                                              "C24010_058E",
                                              "C24010_059E",
                                              "C24010_061E",
                                              "C24010_066E",
                                              "C24010_068E",                         
                                     ), {'for': 'zip code tabulation area:'+str(zip)})
            # Convert to DataFrame
            census_pd = pd.DataFrame(census_data)
            census_pd["Year"]=yr
            # Column Reordering
            census_pd = census_pd.rename(columns={"B01003_001E": "Population", 
                                                  "B01002_001E": "Median Age",
                                                  "B19013_001E": "Household Income",
                                                  "B19301_001E": "Per Capita Income",
                                                  "B17001_002E": "Poverty Count",
                                                  "B23025_002E": "Employment Count",
                                                  "B23025_005E": "Unemployment Count",
                                                  "B25077_001E": "Median Home Value",
                                                  "B25064_001E": "Median Gross Rent",                                      
                                                  "C24010_009E": "Emp Male Arch Engnr",
                                                  "C24010_016E": "Emp Male Health Prac",
                                                  "C24010_019E": "Emp Male Service Occ",
                                                  "C24010_022E": "Emp Male Fire Prev",
                                                  "C24010_023E": "Emp Male Law Enfrcmnt",
                                                  "C24010_025E": "Emp Male BldgGrnd Cleaning",
                                                  "C24010_030E": "Emp Male Ntrl Rsrces Const",
                                                  "C24010_032E": "Emp Male Const Extrctn",                                      
                                                  "C24010_045E": "Emp FMale Arch Engnr",
                                                  "C24010_052E": "Emp FMale Health Prac",
                                                  "C24010_055E": "Emp FMale Service Occ",
                                                  "C24010_058E": "Emp FMale Fire Prev",
                                                  "C24010_059E": "Emp FMale Law Enfrcmnt",
                                                  "C24010_061E": "Emp FMale BldgGrnd Cleaning",
                                                  "C24010_066E": "Emp FMale Ntrl Rsrces Const",
                                                  "C24010_068E": "Emp FMale Const Extrctn",                                                                          
                                                  "NAME": "Name",                                       
                                                  "zip code tabulation area": "Zip",
                                                  "Year":"Year"})

            census_pd["Emp Arch Engnr"]=census_pd["Emp Male Arch Engnr"]+census_pd["Emp FMale Arch Engnr"]
            census_pd["Emp Health Prac"]=census_pd["Emp Male Health Prac"]+census_pd["Emp FMale Health Prac"]
            census_pd["Emp Service Occ"]=census_pd["Emp Male Service Occ"]+census_pd["Emp FMale Service Occ"]
            census_pd["Emp Fire Prev"]=census_pd["Emp Male Fire Prev"]+census_pd["Emp FMale Fire Prev"]
            census_pd["Emp Law Enfrcmnt"]=census_pd["Emp Male Law Enfrcmnt"]+census_pd["Emp FMale Law Enfrcmnt"]
            census_pd["Emp BldgGrnd Cleaning"]=census_pd["Emp Male BldgGrnd Cleaning"]+census_pd["Emp FMale BldgGrnd Cleaning"]
            census_pd["Emp Ntrl Rsrces Const"]=census_pd["Emp Male Ntrl Rsrces Const"]+census_pd["Emp FMale Ntrl Rsrces Const"]
            census_pd["Emp Const Extrctn"]=census_pd["Emp Male Const Extrctn"]+census_pd["Emp FMale Const Extrctn"]

            # Add in Poverty Rate (Poverty Count / Population)
            census_pd["Poverty Rate"] = 100 * census_pd["Poverty Count"].astype(int) / census_pd["Population"].astype(int)

            # Add in Employment Rate (Employment Count / Population)
            census_pd["Unemployment Rate"] = 100 * census_pd["Unemployment Count"].astype(int) / census_pd["Population"].astype(int)

            # Final DataFrame
            census_pd = census_pd[["Year",                       
                                   "Name", 
                                   "Zip",
                                   "Population", 
                                   "Median Age", 
                                   "Household Income",
                                   "Per Capita Income", 
                                   "Poverty Count", 
                                   "Poverty Rate",
                                   "Employment Count", 
                                   "Unemployment Rate",
                                   "Median Home Value",
                                   "Median Gross Rent",
                                   "Emp Arch Engnr",
                                   "Emp Health Prac",
                                   "Emp Service Occ",
                                   "Emp Fire Prev",
                                   "Emp Law Enfrcmnt",
                                   "Emp BldgGrnd Cleaning",
                                   "Emp Ntrl Rsrces Const",
                                   "Emp Const Extrctn"
                                   ]]                 

            if ctr==1:
                print("Creating from year "+str(yr)+"...")
                census_pd_test=census_pd
            else:
                print("appending year "+str(yr)+"...")
                census_pd_test=census_pd_test.append(census_pd)
            ctr+=1
        except:
            print("No Data")
        yr+=1

Creating from year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
No Data
No Data
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
No Data
No Data
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...
appending year 2012...
appending year 2013...

In [4]:
census_pd_test2012=census_pd_test.loc[census_pd_test["Year"]==2012]
census_pd_test2013=census_pd_test.loc[census_pd_test["Year"]==2013]

In [9]:
census_pd_testmrg=pd.merge(census_pd_test2013, census_pd_test2012, on="Zip")
census_pd_testmrg

,Year_x,Name_x,Zip,Population_x,Median Age_x,Household Income_x,Per Capita Income_x,Poverty Count_x,Poverty Rate_x,Employment Count_x,...,Median Home Value_y,Median Gross Rent_y,Emp Arch Engnr_y,Emp Health Prac_y,Emp Service Occ_y,Emp Fire Prev_y,Emp Law Enfrcmnt_y,Emp BldgGrnd Cleaning_y,Emp Ntrl Rsrces Const_y,Emp Const Extrctn_y
0,2013,ZCTA5 96130,96130,21963.0,35.0,54372.0,18621.0,2847.0,12.962710,6710.0,...,184500.0,877.0,55.0,377.0,2254.0,97.0,1166.0,136.0,472.0,181.0
1,2013,ZCTA5 89406,89406,24572.0,39.2,49830.0,24716.0,3619.0,14.728146,11912.0,...,160100.0,844.0,95.0,378.0,2199.0,145.0,119.0,538.0,1133.0,470.0
2,2013,ZCTA5 95501,95501,23704.0,37.0,37600.0,21122.0,4968.0,20.958488,12342.0,...,270700.0,793.0,147.0,332.0,3071.0,216.0,141.0,669.0,1232.0,863.0
3,2013,ZCTA5 93117,93117,54251.0,21.9,56669.0,22722.0,12866.0,23.715692,29618.0,...,666200.0,1445.0,698.0,1256.0,6288.0,489.0,72.0,1384.0,1313.0,695.0
4,2013,ZCTA5 82520,82520,13778.0,39.3,56554.0,24971.0,1549.0,11.242561,7138.0,...,205100.0,632.0,73.0,431.0,1411.0,92.0,27.0,436.0,819.0,559.0
5,2013,ZCTA5 73013,73013,46457.0,34.7,75741.0,38470.0,3761.0,8.095658,24288.0,...,185000.0,997.0,629.0,2075.0,2567.0,235.0,111.0,280.0,1161.0,652.0
6,2013,ZCTA5 95422,95422,15427.0,41.6,25460.0,16552.0,5484.0,35.548065,6350.0,...,104300.0,750.0,25.0,184.0,1361.0,15.0,87.0,155.0,948.0,399.0
7,2013,ZCTA5 73020,73020,21499.0,40.1,67088.0,29985.0,2051.0,9.539979,10611.0,...,150300.0,784.0,206.0,596.0,1295.0,187.0,109.0,199.0,1305.0,743.0
8,2013,ZCTA5 95540,95540,12877.0,38.7,40751.0,21707.0,2543.0,19.748389,5336.0,...,292900.0,784.0,32.0,200.0,1160.0,35.0,149.0,398.0,606.0,215.0
9,2013,ZCTA5 75964,75964,19648.0,32.8,35827.0,17313.0,6085.0,30.970073,8920.0,...,78200.0,677.0,52.0,451.0,1316.0,25.0,87.0,346.0,1243.0,729.0
10,2013,ZCTA5 93555,93555,32376.0,36.4,61221.0,28697.0,4515.0,13.945515,15835.0,...,185200.0,800.0,1244.0,533.0,2049.0,165.0,195.0,460.0,1543.0,589.0
11,2013,ZCTA5 93561,93561,34851.0,39.3,57433.0,24708.0,3665.0,10.516198,13276.0,...,229300.0,902.0,380.0,620.0,3305.0,168.0,965.0,618.0,1514.0,718.0
12,2013,ZCTA5 92284,92284,24951.0,38.1,41398.0,20534.0,4835.0,19.377981,10451.0,...,156200.0,878.0,68.0,628.0,1552.0,59.0,114.0,400.0,1495.0,893.0
13,2013,ZCTA5 75652,75652,16185.0,39.4,42778.0,19036.0,2058.0,12.715477,5802.0,...,91600.0,621.0,40.0,201.0,1309.0,81.0,170.0,226.0,802.0,545.0
14,2013,ZCTA5 89433,89433,19630.0,34.2,41639.0,17272.0,4454.0,22.689761,9702.0,...,116300.0,967.0,89.0,169.0,2057.0,196.0,34.0,671.0,845.0,585.0
15,2013,ZCTA5 93212,93212,25618.0,36.1,33756.0,8700.0,3973.0,15.508627,5738.0,...,137400.0,812.0,12.0,109.0,842.0,23.0,132.0,141.0,1491.0,269.0
16,2013,ZCTA5 90275,90275,42051.0,49.0,118860.0,57705.0,1884.0,4.480274,18969.0,...,974900.0,2001.0,1047.0,1853.0,1036.0,211.0,92.0,59.0,326.0,131.0
17,2013,ZCTA5 93436,93436,54433.0,34.0,52032.0,22926.0,10073.0,18.505318,24231.0,...,277200.0,995.0,613.0,908.0,5504.0,527.0,368.0,1397.0,3044.0,1095.0
18,2013,ZCTA5 96150,96150,28686.0,40.0,46859.0,25479.0,4443.0,15.488392,16574.0,...,364100.0,969.0,188.0,513.0,5299.0,472.0,188.0,1460.0,1493.0,867.0

In [8]:
#census_pd_testmrg=census_pd_testmrg.loc[(census_pd_testmrg["Population_x"]>=1100) & (census_pd_testmrg["Population_x"]<=35000)]
#census_pd_testmrg

,Year_x,Name_x,Zip,Population_x,Median Age_x,Household Income_x,Per Capita Income_x,Poverty Count_x,Poverty Rate_x,Employment Count_x,...,Median Home Value_y,Median Gross Rent_y,Emp Arch Engnr_y,Emp Health Prac_y,Emp Service Occ_y,Emp Fire Prev_y,Emp Law Enfrcmnt_y,Emp BldgGrnd Cleaning_y,Emp Ntrl Rsrces Const_y,Emp Const Extrctn_y
0,2013,ZCTA5 96130,96130,21963.0,35.0,54372.0,18621.0,2847.0,12.962710,6710.0,...,184500.0,877.0,55.0,377.0,2254.0,97.0,1166.0,136.0,472.0,181.0
1,2013,ZCTA5 89406,89406,24572.0,39.2,49830.0,24716.0,3619.0,14.728146,11912.0,...,160100.0,844.0,95.0,378.0,2199.0,145.0,119.0,538.0,1133.0,470.0
2,2013,ZCTA5 95501,95501,23704.0,37.0,37600.0,21122.0,4968.0,20.958488,12342.0,...,270700.0,793.0,147.0,332.0,3071.0,216.0,141.0,669.0,1232.0,863.0
4,2013,ZCTA5 82520,82520,13778.0,39.3,56554.0,24971.0,1549.0,11.242561,7138.0,...,205100.0,632.0,73.0,431.0,1411.0,92.0,27.0,436.0,819.0,559.0
6,2013,ZCTA5 95422,95422,15427.0,41.6,25460.0,16552.0,5484.0,35.548065,6350.0,...,104300.0,750.0,25.0,184.0,1361.0,15.0,87.0,155.0,948.0,399.0
7,2013,ZCTA5 73020,73020,21499.0,40.1,67088.0,29985.0,2051.0,9.539979,10611.0,...,150300.0,784.0,206.0,596.0,1295.0,187.0,109.0,199.0,1305.0,743.0
8,2013,ZCTA5 95540,95540,12877.0,38.7,40751.0,21707.0,2543.0,19.748389,5336.0,...,292900.0,784.0,32.0,200.0,1160.0,35.0,149.0,398.0,606.0,215.0
9,2013,ZCTA5 75964,75964,19648.0,32.8,35827.0,17313.0,6085.0,30.970073,8920.0,...,78200.0,677.0,52.0,451.0,1316.0,25.0,87.0,346.0,1243.0,729.0
10,2013,ZCTA5 93555,93555,32376.0,36.4,61221.0,28697.0,4515.0,13.945515,15835.0,...,185200.0,800.0,1244.0,533.0,2049.0,165.0,195.0,460.0,1543.0,589.0
11,2013,ZCTA5 93561,93561,34851.0,39.3,57433.0,24708.0,3665.0,10.516198,13276.0,...,229300.0,902.0,380.0,620.0,3305.0,168.0,965.0,618.0,1514.0,718.0
12,2013,ZCTA5 92284,92284,24951.0,38.1,41398.0,20534.0,4835.0,19.377981,10451.0,...,156200.0,878.0,68.0,628.0,1552.0,59.0,114.0,400.0,1495.0,893.0
13,2013,ZCTA5 75652,75652,16185.0,39.4,42778.0,19036.0,2058.0,12.715477,5802.0,...,91600.0,621.0,40.0,201.0,1309.0,81.0,170.0,226.0,802.0,545.0
14,2013,ZCTA5 89433,89433,19630.0,34.2,41639.0,17272.0,4454.0,22.689761,9702.0,...,116300.0,967.0,89.0,169.0,2057.0,196.0,34.0,671.0,845.0,585.0
15,2013,ZCTA5 93212,93212,25618.0,36.1,33756.0,8700.0,3973.0,15.508627,5738.0,...,137400.0,812.0,12.0,109.0,842.0,23.0,132.0,141.0,1491.0,269.0
18,2013,ZCTA5 96150,96150,28686.0,40.0,46859.0,25479.0,4443.0,15.488392,16574.0,...,364100.0,969.0,188.0,513.0,5299.0,472.0,188.0,1460.0,1493.0,867.0

In [10]:
census_pd_testsample=census_pd_testmrg

In [11]:
census_pd_testsample

,Year_x,Name_x,Zip,Population_x,Median Age_x,Household Income_x,Per Capita Income_x,Poverty Count_x,Poverty Rate_x,Employment Count_x,...,Median Home Value_y,Median Gross Rent_y,Emp Arch Engnr_y,Emp Health Prac_y,Emp Service Occ_y,Emp Fire Prev_y,Emp Law Enfrcmnt_y,Emp BldgGrnd Cleaning_y,Emp Ntrl Rsrces Const_y,Emp Const Extrctn_y
0,2013,ZCTA5 96130,96130,21963.0,35.0,54372.0,18621.0,2847.0,12.962710,6710.0,...,184500.0,877.0,55.0,377.0,2254.0,97.0,1166.0,136.0,472.0,181.0
1,2013,ZCTA5 89406,89406,24572.0,39.2,49830.0,24716.0,3619.0,14.728146,11912.0,...,160100.0,844.0,95.0,378.0,2199.0,145.0,119.0,538.0,1133.0,470.0
2,2013,ZCTA5 95501,95501,23704.0,37.0,37600.0,21122.0,4968.0,20.958488,12342.0,...,270700.0,793.0,147.0,332.0,3071.0,216.0,141.0,669.0,1232.0,863.0
3,2013,ZCTA5 93117,93117,54251.0,21.9,56669.0,22722.0,12866.0,23.715692,29618.0,...,666200.0,1445.0,698.0,1256.0,6288.0,489.0,72.0,1384.0,1313.0,695.0
4,2013,ZCTA5 82520,82520,13778.0,39.3,56554.0,24971.0,1549.0,11.242561,7138.0,...,205100.0,632.0,73.0,431.0,1411.0,92.0,27.0,436.0,819.0,559.0
5,2013,ZCTA5 73013,73013,46457.0,34.7,75741.0,38470.0,3761.0,8.095658,24288.0,...,185000.0,997.0,629.0,2075.0,2567.0,235.0,111.0,280.0,1161.0,652.0
6,2013,ZCTA5 95422,95422,15427.0,41.6,25460.0,16552.0,5484.0,35.548065,6350.0,...,104300.0,750.0,25.0,184.0,1361.0,15.0,87.0,155.0,948.0,399.0
7,2013,ZCTA5 73020,73020,21499.0,40.1,67088.0,29985.0,2051.0,9.539979,10611.0,...,150300.0,784.0,206.0,596.0,1295.0,187.0,109.0,199.0,1305.0,743.0
8,2013,ZCTA5 95540,95540,12877.0,38.7,40751.0,21707.0,2543.0,19.748389,5336.0,...,292900.0,784.0,32.0,200.0,1160.0,35.0,149.0,398.0,606.0,215.0
9,2013,ZCTA5 75964,75964,19648.0,32.8,35827.0,17313.0,6085.0,30.970073,8920.0,...,78200.0,677.0,52.0,451.0,1316.0,25.0,87.0,346.0,1243.0,729.0
10,2013,ZCTA5 93555,93555,32376.0,36.4,61221.0,28697.0,4515.0,13.945515,15835.0,...,185200.0,800.0,1244.0,533.0,2049.0,165.0,195.0,460.0,1543.0,589.0
11,2013,ZCTA5 93561,93561,34851.0,39.3,57433.0,24708.0,3665.0,10.516198,13276.0,...,229300.0,902.0,380.0,620.0,3305.0,168.0,965.0,618.0,1514.0,718.0
12,2013,ZCTA5 92284,92284,24951.0,38.1,41398.0,20534.0,4835.0,19.377981,10451.0,...,156200.0,878.0,68.0,628.0,1552.0,59.0,114.0,400.0,1495.0,893.0
13,2013,ZCTA5 75652,75652,16185.0,39.4,42778.0,19036.0,2058.0,12.715477,5802.0,...,91600.0,621.0,40.0,201.0,1309.0,81.0,170.0,226.0,802.0,545.0
14,2013,ZCTA5 89433,89433,19630.0,34.2,41639.0,17272.0,4454.0,22.689761,9702.0,...,116300.0,967.0,89.0,169.0,2057.0,196.0,34.0,671.0,845.0,585.0
15,2013,ZCTA5 93212,93212,25618.0,36.1,33756.0,8700.0,3973.0,15.508627,5738.0,...,137400.0,812.0,12.0,109.0,842.0,23.0,132.0,141.0,1491.0,269.0
16,2013,ZCTA5 90275,90275,42051.0,49.0,118860.0,57705.0,1884.0,4.480274,18969.0,...,974900.0,2001.0,1047.0,1853.0,1036.0,211.0,92.0,59.0,326.0,131.0
17,2013,ZCTA5 93436,93436,54433.0,34.0,52032.0,22926.0,10073.0,18.505318,24231.0,...,277200.0,995.0,613.0,908.0,5504.0,527.0,368.0,1397.0,3044.0,1095.0
18,2013,ZCTA5 96150,96150,28686.0,40.0,46859.0,25479.0,4443.0,15.488392,16574.0,...,364100.0,969.0,188.0,513.0,5299.0,472.0,188.0,1460.0,1493.0,867.0

In [12]:
for index,row in census_pd_testsample.iterrows():
    pcchg=(row["Per Capita Income_x"]-row["Per Capita Income_y"])/row["Per Capita Income_y"]
    census_pd_testsample.loc[index,"PCI Change"]=pcchg

In [14]:
census_pd_testsample.to_csv("./Resources/seismic_test_pop.csv")

In [15]:
census_pd_test_ttest=census_pd_testsample[["Zip","PCI Change"]]

In [16]:
census_pd_test_ttest

      Zip  PCI Change
0   96130   -0.033629
1   89406   -0.016631
2   95501   -0.062910
3   93117   -0.028102
4   82520    0.012283
5   73013   -0.020272
6   95422    0.018773
7   73020    0.037902
8   95540   -0.060953
9   75964    0.015842
10  93555   -0.007780
11  93561    0.013911
12  92284   -0.037318
13  75652    0.011746
14  89433    0.001798
15  93212   -0.033118
16  90275   -0.019490
17  93436   -0.010830
18  96150    0.019323

In [17]:
census_pd_test_ttest.to_csv("./Resources/seismic_test_pop_ttest.csv")