In [1]:
## Seismic Analysis Impact on NR&C - T-Test
## By: Fervis Lauan
## Date: 09-29-17
##----------------------------------------------------

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import math

file1 = './Resources/seismic_test_emp_pop_ttest.csv'
seis_test_pop = pd.read_csv(file1)
seis_test_pop

    Unnamed: 0    Zip  Emp Const Extr Change
0            0  96130               0.094763
1            1  89406               0.105940
2            2  95501              -0.138624
3            3  93117               0.186652
4            4  82520               0.057646
5            5  73013              -0.029612
6            6  95422               0.039134
7            7  73020               0.078351
8            8  95540               0.021088
9            9  75964              -0.126543
10          10  93555              -0.013992
11          11  93561              -0.067995
12          12  92284              -0.108707
13          13  75652              -0.074454
14          14  89433               0.085335
15          15  93212               0.066921
16          16  90275               0.138024
17          17  93436               0.045355
18          18  96150               0.006821

In [2]:
file2 = './Resources/seismic_ctrl_emp_pop_ttest.csv'
seis_ctrl_pop = pd.read_csv(file2)
seis_ctrl_pop

     Unnamed: 0    Zip  Emp Const Extr Change
0         27400  78744               0.005919
1          6476  21012              -0.020608
2         15819  48141               0.358491
3          7123  23224               0.056384
4         27793  80002              -0.180728
5         12194  37760              -0.065856
6         11515  35761              -0.016765
7         16164  48854              -0.006387
8         20869  61080              -0.013393
9         16418  49418              -0.130435
10        24406  70815              -0.078708
11        14245  44134               0.026976
12         7914  25504               0.068602
13         7572  24541              -0.106796
14        16436  49445               0.085620
15         2889  11411              -0.172000
16        11516  35763               0.086134
17         4777  15801              -0.241319
18        15256  46802               0.050682
19        10985  33837               0.926829
20         2709  10570              -0.280112
21        26979  77836              -0.089765
22         4884  16101               0.094617
23        31258  95242               0.016959
24         2487   8736              -0.062069
25        19370  57078              -0.013734
26           77    772              -0.170991
27        22237  64113               0.096491
28        21107  61571              -0.051582
29        23373  67530               0.186321
..          ...    ...                    ...
970        4399  15063              -0.071609
971       12887  39565               0.203627
972        9260  29306              -0.232996
973        1984   7026               0.054723
974       10918  33616               0.076443
975       26792  77375              -0.113514
976        7488  24333              -0.075370
977       26916  77571               0.046045
978       27788  79934               0.359511
979        8539  27615              -0.046226
980       17714  53094              -0.067845
981       25231  73025               0.005803
982       13874  43223              -0.075000
983       19734  58103              -0.070010
984       29153  85255               0.453333
985       10557  32693               0.043216
986        5040  16504               0.197302
987       26115  75602               0.157303
988       10777  33193               0.032019
989       25866  75020              -0.138606
990       26015  75254               0.247110
991        9735  30291               0.033163
992       10730  33135               0.149893
993       23292  67357              -0.178784
994       12605  38751              -0.061053
995       27977  80526              -0.084434
996       10606  32806               0.001604
997       29322  85730              -0.054709
998        6555  21208               0.012730
999       10090  31312               0.238889

[1000 rows x 3 columns]

In [3]:
seis_test_pop["Emp Const Extr Change"].mean()

0.01926859492127512

In [4]:
seis_ctrl_pop["Emp Const Extr Change"].mean()

0.010064514751711886

In [5]:
stats.ttest_1samp(a=seis_test_pop["Emp Const Extr Change"], popmean=seis_ctrl_pop["Emp Const Extr Change"].mean())

Ttest_1sampResult(statistic=0.43857323055923036, pvalue=0.66618938399991601)