In [1]:
## Seismic Analysis Impact on PCI - T-Test
## By: Fervis Lauan
## Date: 09-29-17
##----------------------------------------------------

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import math

file1 = './Resources/seismic_test_pop_ttest.csv'
seis_test_pop = pd.read_csv(file1)
seis_test_pop

    Unnamed: 0    Zip  PCI Change
0            0  96130   -0.033629
1            1  89406   -0.016631
2            2  95501   -0.062910
3            3  93117   -0.028102
4            4  82520    0.012283
5            5  73013   -0.020272
6            6  95422    0.018773
7            7  73020    0.037902
8            8  95540   -0.060953
9            9  75964    0.015842
10          10  93555   -0.007780
11          11  93561    0.013911
12          12  92284   -0.037318
13          13  75652    0.011746
14          14  89433    0.001798
15          15  93212   -0.033118
16          16  90275   -0.019490
17          17  93436   -0.010830
18          18  96150    0.019323

In [2]:
file2 = './Resources/seismic_ctrl_pop_ttest.csv'
seis_ctrl_pop = pd.read_csv(file2)
seis_ctrl_pop

     Unnamed: 0    Zip  PCI Change
0          9406  29585   -0.062074
1         27173  78248    0.007755
2          6844  22315    0.012051
3         16244  49048   -0.028741
4          1048   4072    0.038603
5          6580  21236    0.001031
6         30056  90049   -0.045848
7          1069   4105    0.004361
8         27253  78504   -0.052511
9          6544  21158    0.031433
10        18152  54501    0.058915
11        27976  80525    0.010491
12         6678  21704    0.039551
13        29172  85298    0.006284
14        26958  77662    0.029920
15         1838   6437    0.033070
16         7228  23601   -0.031314
17        10164  31605   -0.024800
18          510   2189   -0.042112
19         1720   6071   -0.027464
20        16015  48506    0.035736
21         8407  27263   -0.029227
22        13161  40505    0.005054
23        30586  92618    0.005025
24        29333  85748    0.018742
25        14167  44026    0.016941
26        15260  46806   -0.039769
27        29701  88007    0.050732
28        24714  71909    0.035162
29         8954  28539    0.030660
..          ...    ...         ...
970        2013   7063   -0.056273
971       16839  50208    0.042233
972       12338  38108    0.071060
973       29174  85302   -0.076913
974        4484  15238    0.037528
975        7286  23860    0.024758
976        6246  20110   -0.000203
977       28806  84040    0.031373
978        8448  27370   -0.013803
979       12707  39042    0.016468
980        4431  15122    0.040496
981       27428  78840    0.018715
982       20551  60194    0.038446
983        9575  30009   -0.050570
984       31580  95833    0.017752
985       15223  46750    0.027461
986        9599  30045   -0.026055
987       11511  35757   -0.052732
988       30500  92344   -0.024223
989       17748  53154    0.013445
990       26760  77327    0.006491
991       30969  94070   -0.041032
992        6229  20016   -0.023795
993       16885  50263    0.014473
994       24162  70126   -0.036505
995       25983  75216   -0.063847
996        1865   6482   -0.016550
997       29975  89460   -0.044914
998       27963  80503   -0.000713
999       30859  93619    0.005996

[1000 rows x 3 columns]

In [3]:
seis_test_pop["PCI Change"].mean()

-0.010497626630977449

In [4]:
seis_ctrl_pop["PCI Change"].mean()

0.004651648006269979

In [5]:
stats.ttest_1samp(a=seis_test_pop["PCI Change"], popmean=seis_ctrl_pop["PCI Change"].mean())

Ttest_1sampResult(statistic=-2.3565664182867767, pvalue=0.029976357202402)